# Couchmate Helm Values

env: local

registry:
  name: docker.pkg.github.com
  username: halfmatthalfcat
  email: matt@couchmate.com
  token:

replicas: 3

doToken:

app:
  db:
    host:
    port:
    username:
    password:
    name:
  mailgun:
    apiKey:
    validationKey:

images:
  org: couchmate
  name: server/server
  tag: 0.0.0
