apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-thanos
  labels:
    app.kubernetes.io/subcomponent: thanos
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
      protocol: TCP
  selector:
    app: prometheus
    prometheus: metrics-prometheus-operato-prometheus