apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-sa
imagePullSecrets:
  - name: gh-dockerconfig
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: server-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]