apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchmate
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: server
      env: {{.Values.env}}
  template:
    metadata:
      labels:
        app: server
        env: {{.Values.env}}
    spec:
      serviceAccountName: server-sa
      containers:
        - name: server
          image: "{{.Values.registry.name}}/{{.Values.images.org}}/{{.Values.images.name}}:{{.Values.images.tag}}"
          ports:
            - containerPort: 8080
              name: server-ext
            - containerPort: 2551
              name: server-int
            - containerPort: 8558
              name: management
          env:
            - name: ENV
              value: {{.Values.env}}
            - name: POSTGRES_HOST
              value: {{.Values.app.db.host}}
            - name: POSTGRES_PORT
              value: "{{.Values.app.db.port}}"
            - name: POSTGRES_DB
              value: {{.Values.app.db.name}}
            - name: POSTGRES_USER
              value: {{.Values.app.db.username}}
            - name: POSTGRES_PASSWORD
              value: {{.Values.app.db.password}}
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /alive
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: server
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: couchmate-server
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'false'
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: 'true'
    service.beta.kubernetes.io/do-loadbalancer-algorithm: 'least_connections'
    service.beta.kubernetes.io/do-loadbalancer-protocol: 'https'
    service.beta.kubernetes.io/do-loadbalancer-http-ports: '80'
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: '443'
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: 'http'
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: '8000'
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: '/ready'
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: 'be4dd172-a1fb-46fb-9545-8b1263397535'
    external-dns.alpha.kubernetes.io/hostname: {{if eq .Values.env "prod"}}api{{else}}{{.Values.env}}-api{{end}}.couchmate.com
    external-dns.alpha.kubernetes.io/ttl: "120"
spec:
  type: LoadBalancer
  selector:
    app: server
    env: {{.Values.env}}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: server-ext
    - name: https
      protocol: TCP
      port: 443
      targetPort: server-ext
    - name: management
      protocol: http
      port: 8000
      targetPort: management
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: server
spec:
  rules:
    - host: {{if eq .Values.env "prod"}}api{{else}}{{.Values.env}}-api{{end}}.couchmate.com
      http:
        paths:
          - path: /ws
            backend:
              serviceName: server
              servicePort: 443