apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{.Values.env}}-grafana-cert
spec:
  secretName: {{.Values.env}}-grafana-tls
  issuerRef:
    name: letsencrypt-issuer
  commonName: couchmate.com
  dnsNames:
    - grafana{{if ne .Values.env "prod"}}.{{.Values.env}}{{end}}.couchmate.com