# nginx-ingress helm options

nginx-ingress:
  controller:
    publishService:
      enabled: true
    metrics:
      enabled: true
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: site-nginx-ingress-controller
        service.beta.kubernetes.io/do-loadbalancer-algorithm: 'least_connections'
        service.beta.kubernetes.io/do-loadbalancer-protocol: 'https'
        service.beta.kubernetes.io/do-loadbalancer-http-ports: '80'
        service.beta.kubernetes.io/do-loadbalancer-tls-ports: '443'
        service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: 'true'
        service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: 'true'
        external-dns.alpha.kubernetes.io/ttl: '120'
  defaultBackend:
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: site-nginx-ingress-default-backend
        service.beta.kubernetes.io/do-loadbalancer-algorithm: 'least_connections'
        service.beta.kubernetes.io/do-loadbalancer-protocol: 'http'
        service.beta.kubernetes.io/do-loadbalancer-http-ports: '80'
        service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: '80'
        service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: '/healthz'
