# Couchmate Helm chart
apiVersion: v2
name: server
description: A Helm chart for the Couchmate server

type: application

version: 1.0.0

appVersion: 1.0.0

dependencies:
  - name: external-dns
    version: 3.2.2
    repository: https://charts.bitnami.com/bitnami
  - name: nginx-ingress
    version: 1.40.3
    repository: https://kubernetes-charts.storage.googleapis.com