# Couchmate Server Helmfile

repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ckotzbauer
    url: https://ckotzbauer.github.io/helm-charts

environments:
  default:
    values:
      - env: qa
        metrics:
          enabled: false
  production:
    values:
      - env: prod
        metrics:
          enabled: true

helmDefaults:
  atomic: true
  cleanupOnFail: true
  createNamespace: true

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.1.0
    values:
      - installCRDs: false
  - name: cert-manager-extra
    namespace: cert-manager
    chart: ./cert-manager
    needs:
      - cert-manager/cert-manager
    values:
      - doToken: {{.Values.doToken}}
  - name: external-dns
    namespace: external-dns
    chart: ./external-dns
    values:
      - doToken: {{.Values.doToken}}
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: ./nginx-ingress
    values:
      - ./nginx-ingress/values.yaml.gotmpl
  - name: couchmate
    namespace: couchmate
    chart: ./couchmate
    needs:
      - cert-manager/cert-manager-extra
    values:
      - ./couchmate/values.yaml.gotmpl
  - name: metrics
    namespace: metrics
    chart: ./metrics
    needs:
      - cert-manager/cert-manager-extra
      - couchmate/couchmate
    values:
      - ./metrics/values.yaml.gotmpl
    condition: metrics.enabled