# Couchmate Server Helmfile

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ckotzbauer
    url: https://ckotzbauer.github.io/helm-charts

environments:
  default:
    values:
      - env: qa
  production:
    values:
      - env: prod

helmDefaults:
  atomic: true
  cleanupOnFail: true

releases:
  - name: nginx-ingress
    chart: stable/nginx-ingress
    namespace: nginx-ingress
    version: 1.40.3
    values:
      - nginx-ingress.yaml.gotmpl
  - name: cert-manager
    chart: ./cert-manager
    namespace: cert-manager
    values:
      - ./cert-manager/values.yaml.gotmpl
  - name: metrics
    chart: ./metrics
    namespace: metrics
    values:
      - ./metrics/values.yaml.gotmpl
  - name: couchmate
    namespace: couchmate
    chart: ./couchmate
    needs:
      - cert-manager/cert-manager
    values:
      - ./couchmate/values.yaml.gotmpl
  # Needs to be after couchmate to apply the DO api key secret
  - name: external-dns
    chart: ./external-dns
    namespace: external-dns
    version: 3.2.2
    needs:
      - couchmate/couchmate
    values:
      - ./external-dns/values.yaml.gotmpl
