# Couchmate Helm Values

env: local

registry:
  name: docker.pkg.github.com
  username: halfmatthalfcat
  email: matt@couchmate.com
  token:

replicas: 3

doToken:

app:
  db:
    host:
    port:
    username:
    password:
    name:
  mailgun:
    apiKey:
    validationKey:

images:
  org: couchmate
  name: server/server
  tag: 0.0.0

external-dns:
  domainFilters:
    - couchmate.com
  digitalocean:
    secretName: digitalocean-apikey
nginx-ingress:
  controller:
    metrics:
      enabled: true
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: nginx-ingress-controller
        service.beta.kubernetes.io/do-loadbalancer-algorithm: 'least_connections'
        service.beta.kubernetes.io/do-loadbalancer-protocol: 'https'
        service.beta.kubernetes.io/do-loadbalancer-http-ports: '80'
        service.beta.kubernetes.io/do-loadbalancer-tls-ports: '443'
        service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: 'true'
        service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: 'true'
  defaultBackend:
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: nginx-ingress-default-backend
        service.beta.kubernetes.io/do-loadbalancer-algorithm: 'least_connections'
        service.beta.kubernetes.io/do-loadbalancer-protocol: 'http'
        service.beta.kubernetes.io/do-loadbalancer-http-ports: '80'
        service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: '80'
        service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: '/healthz'
