# Couchmate Helm Values

env: dev

registry:
  name: docker.pkg.github.com
  username: halfmatthalfcat
  email: matt@couchmate.com
  token:

replicas: 3

app:
  db:
    host:
    port:
    username:
    password:
    name:

images:
  org: couchmate
  name: server/server
  tag: 0.0.0

external-dns:
  provider: cloudflare
  domainFilters:
    - couchmate.com
  zoneIdFilters:
    - 53e5a461e6830e20f9f56f9bac1d9da9
  cloudflare:
    apiToken:
    email: matt@couchmate.com
    proxied: true