{
 "title": "Application",
 "description": "Application Health and Metrics",
 "tags": [
  "health",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cm_sessions)" }
   ]
  },
  {
   "title": "Current Attendance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cm_attendance)" }
   ]
  },
  {
   "title": "Rooms Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cm_rooms)" }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cm_messages)" }
   ]
  },
  {
   "title": "Sessions Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cm_sessions) by (provider)", "legendFormat": "{{provider}}" }
   ]
  },
  {
   "title": "Registered Accounts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cm_registered)", "legendFormat": "sum" },
    {
     "expr": "sum(increase(cm_registered[1m]))",
     "legendFormat": "increase"
    }
   ]
  },
  {
   "title": "Time In Room",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cm_time_in_room_sum[$__range])) / sum(rate(cm_time_in_room_count[$__range]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cm_time_in_room_bucket[1m])) by (le))",
     "legendFormat": "95% CI"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cm_time_in_room_bucket[1m])) by (le))",
     "legendFormat": "99% CI"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cm_messages)", "legendFormat": "sum" },
    { "expr": "sum(increase(cm_messages[1m]))", "legendFormat": "increase" }
   ]
  },
  {
   "title": "Attendence",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cm_attendance) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Rooms Created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cm_rooms)", "legendFormat": "sum" },
    { "expr": "sum(increase(cm_rooms[1m]))", "legendFormat": "increase" }
   ]
  }
 ]
}