apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@couchmate.com
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-apikey
              key: digitalocean_api_token
