apiVersion: v1
kind: Secret
metadata:
  name: data-providers-secret
stringData:
  datasource.yaml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://metrics-prometheus-operato-prometheus:9090
        isDefault: true
        editable: false
