apiVersion: v1
kind: Secret
metadata:
  name: data-providers-secret
stringData:
  datasource.yaml: |-
    apiVersion: 1

    datasources:
      - name: Timescale PromQL
        type: prometheus
        access: proxy
        orgId: 1
        url: http://metrics-timescale-prometheus-connector:9201
        isDefault: true
        editable: false
      - name: Timescale Postgres
        type: postgres
        access: proxy
        orgId: 1
        url: {{.Values.tsdbHost}}:{{.Values.tsdbPort}}
        user: doadmin
        database: {{.Values.tsdbName}}
        isDefault: false
        editable: false
        secureJsonData:
          password: {{.Values.tsdbPassword}}
        jsonData:
          postgresVersion: 1200
          timescaledb: true
          sslmode: require
