apiVersion: v1
kind: Secret
metadata:
  name: data-providers-secret
stringData:
  datasource.yaml: |-
    apiVersion: 1

    datasources:
      - name: Thanos
        type: prometheus
        access: proxy
        orgId: 1
        url: http://metrics-thanos-querier:9090
        isDefault: false
        editable: false
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://metrics-kube-prometheus-prometheus:9090
        isDefault: true
        editable: false
