-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDXnn8Y6Gluqx9JSm
Q2T/pdjIM6fq+P581BrRofAcIz+gCgYIKoZIzj0DAQehRANCAARQJGKM5zEvvXs2
DkLkhxfioLhl4UTFOoq+1SL7UFSq0ssCUXtGBQQNrcSIaMKkTeeHKu1W56CYacjB
yFrnUgEx
-----END PRIVATE KEY-----