apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-{{.Values.env}}-metrics-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-{{.Values.env}}-metrics-proxy
  template:
    metadata:
      labels:
        app: cm-{{.Values.env}}-metrics-proxy
    spec:
      containers:
        - args:
            - --provider=google
            - --email-domain=couchmate.com
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: {{.Values.clientId}}
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: {{.Values.clientSecret}}
            - name: OAUTH2_PROXY_COOKIE_SECRET
              # For now, on every release it'll update this value
              # People will have to re-login...if it becomes an issue
              # we can just change it to a static value
              value: "{{ randAscii 32 }}"
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cm-{{.Values.env}}-metrics-proxy
  name: cm-{{.Values.env}}-metrics-proxy
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    app: cm-{{.Values.env}}-metrics-proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cm-{{.Values.env}}-metrics-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-issuer
spec:
  rules:
    - host: prometheus{{if ne .Values.env "prod"}}.{{.Values.env}}{{end}}.couchmate.com
      http:
        paths:
          - backend:
              serviceName: cm-{{.Values.env}}-metrics-proxy
              servicePort: 4180
            path: /oauth2
    - host: grafana{{if ne .Values.env "prod"}}.{{.Values.env}}{{end}}.couchmate.com
      http:
        paths:
          - backend:
              serviceName: cm-{{.Values.env}}-metrics-proxy
              servicePort: 4180
            path: /oauth2
  tls:
    - hosts:
        - prometheus{{if ne .Values.env "prod"}}.{{.Values.env}}{{end}}.couchmate.com
        - grafana{{if ne .Values.env "prod"}}.{{.Values.env}}{{end}}.couchmate.com
      secretName: {{.Values.env}}-metrics-tls