apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: cert-manager
    version: v0.16.0
    repository: https://charts.jetstack.io