apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.env}}-api-cert
spec:
  secretName: {{.Values.env}}-api-tls
  issuerRef:
    name: letsencrypt-issuer
  commonName: couchmate.com
  dnsNames:
    - {{if eq .Values.env "prod"}}api{{else}}{{.Values.env}}-api{{end}}.couchmate.com