name: Release

on:
  release:
    types: [ published ]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout release
        run : git branch --track master origin/master && git reset --hard tags/${{ github.event.release.tag_name }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Release
        run : sbt "release release-version ${{ github.event.release.tag_name }} with-defaults"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: Matt Oliver
          GIT_AUTHOR_EMAIL: matt@couchmate.com
      - name: Generate Typescript Definitions
        run : sbt tsTranspile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Typescript Definitions
        uses: actions/upload-artifact@v1
        with:
          name: typescript
          path: target/typescript
  uploadTS:
    runs-on: ubuntu-latest
    needs: [ version ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@couchmate'
      - name: Download typescript definitions
        uses: actions/download-artifact@v1
        with:
          name: typescript
      - name: Upload typescript definitions
        run : npm publish target/typescript
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
