name: Release

on:
  release:
    types: [ published ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Build Output
        id: sbt-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
  artifacts:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@couchmate'
      - name: Install Dependencies
        if: steps.sbt-cache.outputs.cache-hit != 'true'
        run: sbt "update; webNodeModules"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Login
        run: docker login https://docker.pkg.github.com -u halfmatthalfcat -p ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout release
        run : |
          git branch --track master origin/master && git reset --hard tags/${{ github.event.release.tag_name }}
          git config --global user.email "matt@couchmate.com"
          git config --global user.name "Matt Oliver"
      - name: Run Release
        run : sbt "project core; release release-version ${{ github.event.release.tag_name }} with-defaults"
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Typescript Definitions
        run : sbt "webNodeModules; tsTranspile"
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Typescript Definitions
        uses: actions/upload-artifact@v2
        with:
          name: typescript
          path: core/target/typescript
      - name: Publish Typescript definitions
        run: npm publish ./core/target/typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: [ artifacts ]
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Set cluster
        run: doctl kubernetes cluster kubeconfig save dev-east
      - name: Prep helm
        run: helm plugin install https://github.com/sstarcher/helm-release
      - name: Version chart
        run: helm release ./chart -t ${{ github.event.release.tag_name }}
      - name: Release chart
        run: helm upgrade --install --atomic --cleanup-on-fail --set registry.token=${{ secrets.GITHUB_TOKEN }},external-dns.cloudflare.apiKey=${{ secrets.CF_TOKEN }} couchmate ./charts