name: Release

on:
  release:
    types: [ published ]

jobs:
  version:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Build Output
        id: sbt-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Install Dependencies
        if: steps.sbt-cache.outputs.cache-hit != 'true'
        run: sbt update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout release
        run : |
          git branch --track master origin/master && git reset --hard tags/${{ github.event.release.tag_name }}
          git config --global user.email "matt@couchmate.com"
          git config --global user.name "Matt Oliver"
      - name: Run Release
        run : sbt "release release-version ${{ github.event.release.tag_name }} with-defaults"
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Typescript Definitions
        run : sbt "update; tsTranspile"
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Typescript Definitions
        uses: actions/upload-artifact@v1
        with:
          name: typescript
          path: target/typescript
  uploadTS:
    runs-on: ubuntu-latest
    needs: [ install, version ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@couchmate'
      - name: Download typescript definitions
        uses: actions/download-artifact@v1
        with:
          name: typescript
      - name: Upload typescript definitions
        run : npm publish target/typescript
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
